"""Gmail SMTP email sender for meal plan notifications."""

import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from config import (
    GMAIL_APP_PASSWORD_ENV,
    GMAIL_RECIPIENTS,
    GMAIL_SENDER,
    SMTP_HOST,
    SMTP_PORT,
)


def get_app_password() -> str:
    """Get Gmail app password from environment variable."""
    password = os.environ.get(GMAIL_APP_PASSWORD_ENV)
    if not password:
        raise RuntimeError(
            f"Environment variable {GMAIL_APP_PASSWORD_ENV} is not set. "
            "Generate an app password at https://myaccount.google.com/apppasswords"
        )
    return password


def format_email_html(meals: list, date: str) -> str:
    """Format meal plan as an HTML email body."""
    notion_meals = [m for m in meals if m["source"] == "notion"]
    web_meals = [m for m in meals if m["source"] == "web"]

    def meal_list_html(items: list) -> str:
        if not items:
            return "<li><em>None selected</em></li>"
        return "".join(
            '<li><a href="{url}">{name}</a></li>'.format(
                url=m["url"], name=m["recipe_name"]
            )
            for m in items
        )

    return """\
<html>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
  <h2>Meal Prep Plan — week of {date}</h2>

  <h3>From Notion</h3>
  <ul>{notion_list}</ul>

  <h3>New Recipe (Web)</h3>
  <ul>{web_list}</ul>

  <hr style="margin-top: 30px; border: none; border-top: 1px solid #ccc;">
  <p style="color: #888; font-size: 12px;">Generated by meal-planner</p>
</body>
</html>""".format(
        date=date,
        notion_list=meal_list_html(notion_meals),
        web_list=meal_list_html(web_meals),
    )


def send_email(subject: str, html_body: str) -> None:
    """Send an email via Gmail SMTP."""
    password = get_app_password()

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = GMAIL_SENDER
    msg["To"] = ", ".join(GMAIL_RECIPIENTS)
    msg.attach(MIMEText(html_body, "html"))

    with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
        server.starttls()
        server.login(GMAIL_SENDER, password)
        server.sendmail(GMAIL_SENDER, GMAIL_RECIPIENTS, msg.as_string())


def send_meal_plan_email(meals: list, date: str) -> None:
    """Send the weekly meal plan email."""
    html = format_email_html(meals, date)
    send_email("Meal Prep Plan — Week of %s" % date, html)


def send_revised_meal_plan_email(meals: list, date: str) -> None:
    """Send a revised meal plan email with 'Revised' in the subject."""
    html = format_email_html(meals, date)
    send_email("Meal Prep Plan — Revised — Week of %s" % date, html)


def send_failure_email(error_message: str) -> None:
    """Attempt to send a failure notification email."""
    html = """\
<html>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
  <h2 style="color: #c0392b;">Meal Planner Error</h2>
  <p>The weekly meal planner failed to run:</p>
  <pre style="background: #f5f5f5; padding: 15px; border-radius: 5px; overflow-x: auto;">{error}</pre>
  <p>Check the logs for more details.</p>
</body>
</html>""".format(error=error_message)
    send_email("Meal Planner — Error", html)
